#!/bin/bash

# This test file will be executed against after building a container with the
# 'release-0-9' scenario in 'test/test/neovim/scenarios.json'.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This scenario first uses the 'common-utils' Features to add a new user 'octocat'. 
# It then installs the 'neovim' Feature with the FAVORITE option set to 'green' (the default FAVORITE value if none provided is 'red').
#
# 
# This test (as well as any of the other scenarios in 'scenarios.json') can be run with the following command:
#
#    devcontainer features test \ 
#               --features neovim \
#               --skip-autogenerated \
#               /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib.
check "validate successful install" bash -c "nvim --version grep 'NVIM v0.9.0'"

# Report result
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
